package database

import (
	"time"
)

// TransactionSource records whether a transaction was entered by hand or
// generated by the recurring-template scheduler. It is purely informational
// — a recurring-sourced transaction remains fully editable afterwards.
type TransactionSource string

const (
	SourceManual    TransactionSource = "manual"
	SourceRecurring TransactionSource = "recurring"
)

const dateLayout = "2006-01-02"

// Transaction is a single booking. AmountCents is always a positive
// magnitude; whether it counts as income or expense is determined by its
// category's Type.
type Transaction struct {
	ID          int64
	AmountCents int64
	Date        time.Time
	Description string
	CategoryID  int64
	AccountID   int64
	Source      TransactionSource
	CreatedAt   time.Time
}

// TransactionDetail is a Transaction enriched with the display fields of its
// category and account, as needed by the overview list.
type TransactionDetail struct {
	Transaction
	CategoryName  string
	CategoryColor string
	CategoryType  CategoryType
	AccountName   string
}

const transactionDetailQuery = `
	SELECT
		t.id, t.amount_cents, t.date, t.description, t.category_id, t.account_id, t.source, t.created_at,
		c.name, c.color, c.type,
		a.name
	FROM transactions t
	JOIN categories c ON c.id = t.category_id
	JOIN accounts a ON a.id = t.account_id
`

func scanTransactionDetail(row interface{ Scan(...any) error }) (TransactionDetail, error) {
	var td TransactionDetail
	var dateStr string
	var source, catType string
	err := row.Scan(
		&td.ID, &td.AmountCents, &dateStr, &td.Description, &td.CategoryID, &td.AccountID, &source, &td.CreatedAt,
		&td.CategoryName, &td.CategoryColor, &catType,
		&td.AccountName,
	)
	if err != nil {
		return TransactionDetail{}, err
	}
	td.Date, err = time.Parse(dateLayout, dateStr)
	if err != nil {
		return TransactionDetail{}, err
	}
	td.Source = TransactionSource(source)
	td.CategoryType = CategoryType(catType)
	return td, nil
}

// ListTransactions returns all transactions, newest first. If limit > 0, at
// most that many are returned.
func (s *Store) ListTransactions(limit int) ([]TransactionDetail, error) {
	query := transactionDetailQuery + ` ORDER BY t.date DESC, t.id DESC`
	args := []any{}
	if limit > 0 {
		query += ` LIMIT ?`
		args = append(args, limit)
	}

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var out []TransactionDetail
	for rows.Next() {
		td, err := scanTransactionDetail(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, td)
	}
	return out, rows.Err()
}

// ListTransactionsInMonth returns all transactions dated within the given
// year/month, newest first.
func (s *Store) ListTransactionsInMonth(year int, month time.Month) ([]TransactionDetail, error) {
	start, end := monthRange(year, month)
	rows, err := s.db.Query(
		transactionDetailQuery+` WHERE t.date >= ? AND t.date < ? ORDER BY t.date DESC, t.id DESC`,
		start.Format(dateLayout), end.Format(dateLayout),
	)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var out []TransactionDetail
	for rows.Next() {
		td, err := scanTransactionDetail(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, td)
	}
	return out, rows.Err()
}

// MonthSummary returns total income and expense (both positive magnitudes)
// booked in the given year/month.
func (s *Store) MonthSummary(year int, month time.Month) (incomeCents, expenseCents int64, err error) {
	start, end := monthRange(year, month)
	err = s.db.QueryRow(`
		SELECT
			COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount_cents ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount_cents ELSE 0 END), 0)
		FROM transactions t
		JOIN categories c ON c.id = t.category_id
		WHERE t.date >= ? AND t.date < ?
	`, start.Format(dateLayout), end.Format(dateLayout)).Scan(&incomeCents, &expenseCents)
	return incomeCents, expenseCents, err
}

func monthRange(year int, month time.Month) (start, end time.Time) {
	start = time.Date(year, month, 1, 0, 0, 0, 0, time.UTC)
	end = start.AddDate(0, 1, 0)
	return start, end
}

// GetTransactionDetail fetches a single transaction by ID, enriched with
// its category and account display fields.
func (s *Store) GetTransactionDetail(id int64) (TransactionDetail, error) {
	row := s.db.QueryRow(transactionDetailQuery+` WHERE t.id = ?`, id)
	return scanTransactionDetail(row)
}

// GetTransaction fetches a single transaction by ID.
func (s *Store) GetTransaction(id int64) (Transaction, error) {
	var t Transaction
	var dateStr, source string
	err := s.db.QueryRow(
		`SELECT id, amount_cents, date, description, category_id, account_id, source, created_at
		 FROM transactions WHERE id = ?`, id,
	).Scan(&t.ID, &t.AmountCents, &dateStr, &t.Description, &t.CategoryID, &t.AccountID, &source, &t.CreatedAt)
	if err != nil {
		return Transaction{}, err
	}
	t.Date, err = time.Parse(dateLayout, dateStr)
	t.Source = TransactionSource(source)
	return t, err
}

// CreateTransaction inserts a new transaction.
func (s *Store) CreateTransaction(amountCents int64, date time.Time, description string, categoryID, accountID int64, source TransactionSource) (Transaction, error) {
	res, err := s.db.Exec(
		`INSERT INTO transactions (amount_cents, date, description, category_id, account_id, source)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		amountCents, date.Format(dateLayout), description, categoryID, accountID, string(source),
	)
	if err != nil {
		return Transaction{}, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return Transaction{}, err
	}
	return s.GetTransaction(id)
}

// UpdateTransaction updates the editable fields of a transaction. The
// source flag (manual/recurring) is left untouched.
func (s *Store) UpdateTransaction(id int64, amountCents int64, date time.Time, description string, categoryID, accountID int64) (Transaction, error) {
	if _, err := s.db.Exec(
		`UPDATE transactions SET amount_cents = ?, date = ?, description = ?, category_id = ?, account_id = ?
		 WHERE id = ?`,
		amountCents, date.Format(dateLayout), description, categoryID, accountID, id,
	); err != nil {
		return Transaction{}, err
	}
	return s.GetTransaction(id)
}

// DeleteTransaction removes a transaction.
func (s *Store) DeleteTransaction(id int64) error {
	_, err := s.db.Exec(`DELETE FROM transactions WHERE id = ?`, id)
	return err
}
